"""GitHub, connected read-only to scan Terraform for its priced shape.

Unlike the other adapters in this package, this one is not reading a
bill: there is no GitHub billing API to call. It reads the repository's
own `.tf` files, parses the resources and terraform-aws-modules calls
they declare, and prices each one against the same catalog every other
page in this app prices against. A repo generated by this app's own
`/plan/export.tf` or `/describe/export.tf` is the case this is built to
parse cleanly, since it names the exact modules and attributes below.

WHAT THIS IS NOT: a live cost reader. `/api/finops/live` deliberately
501s every non-AWS provider, with the reason recorded there -- fabricated
"live" numbers, shown as if real, is a documented past incident this
codebase guards against. This module's numbers are a PREDICTION from
static code, not a bill, and the caller must not present them as one.

THE TOKEN IS NEVER PERSISTED. It is read out of `config` for the one
fetch this call makes and is not written to `VerifyResult`, logged, or
handed to `store.save_connection` -- see `connection_verify` in api.py,
which strips it from the config dict before saving.

NEVER INVENT A PRICE. A resource whose size comes from a Terraform
variable this module did not resolve, or a module (like the S3 bucket
module) whose own arguments never carry a size at all, is reported in
`missing` with the specific reason -- the same rule `estimator.py`'s
module docstring states for the forward (spec -> price) direction.
"""

from __future__ import annotations

import io
from dataclasses import dataclass
from decimal import Decimal

import httpx

from ..pricing import store
from ..pricing.models import HOURS_PER_MONTH
from .models import Setup, SetupStep, VerifyResult

_API = "https://api.github.com"
_TIMEOUT = 15

#: Abuse guardrails. A repo with thousands of files is not what this
#: reads for -- stop collecting once either limit is hit and price
#: whatever was already fetched, rather than fetching forever or failing
#: the whole scan over one oversized repo.
_MAX_FILES = 50
_MAX_BYTES = 2_000_000

#: How deep to walk subdirectories under `iac_path`. Two levels covers a
#: flat main.tf plus the modules/*.tf split terraform_export.py itself
#: produces; a repo organised much deeper than that is out of scope for
#: this pass.
_MAX_DEPTH = 2

#: Regions worth trying, in order, when the Terraform itself declares
#: none: WhichCloud defaults to India everywhere else in this app, so a
#: scan that finds no `aws_region`/`region` variable prices against the
#: same default rather than an arbitrary one.
_DEFAULT_REGION = "ap-south-1"


def _owner_repo(repo_url: str) -> tuple[str, str]:
    """`owner/repo`, however it was typed.

    Accepts a bare `owner/repo`, a full `https://github.com/owner/repo`
    URL, or the same with a trailing `.git` -- all three are things a
    person reasonably pastes here.
    """
    s = repo_url.strip()
    for prefix in ("https://github.com/", "http://github.com/", "github.com/"):
        if s.lower().startswith(prefix):
            s = s[len(prefix):]
            break
    s = s.strip("/")
    if s.endswith(".git"):
        s = s[: -len(".git")]
    parts = s.split("/")
    if len(parts) < 2 or not parts[0] or not parts[1]:
        raise ValueError(
            f"{repo_url!r} does not look like a GitHub repository "
            "(expected owner/repo or a github.com URL)."
        )
    return parts[0], parts[1]


def _explain(response: httpx.Response, owner: str, repo: str, branch: str, path: str) -> str:
    if response.status_code in (401, 403):
        return (
            f"GitHub refused to read {owner}/{repo}. The token is missing, "
            "expired, or does not have read access to this repository."
        )
    if response.status_code == 404:
        return (
            f"Could not find {owner}/{repo} at branch {branch!r}, path "
            f"{path!r}. Check the repository name, that the branch "
            "exists, and that the path is correct."
        )
    try:
        message = response.json().get("message", "")
    except Exception:
        message = response.text[:200]
    return f"GitHub returned {response.status_code}: {message}"


@dataclass
class _Entry:
    path: str
    kind: str  # "file" | "dir"


def _list_dir(client: httpx.Client, owner: str, repo: str, branch: str, path: str) -> list[_Entry]:
    url = f"{_API}/repos/{owner}/{repo}/contents/{path}".rstrip("/")
    response = client.get(url, params={"ref": branch})
    if response.status_code >= 400:
        raise ValueError(_explain(response, owner, repo, branch, path))
    body = response.json()
    # A path that names a FILE, not a directory, comes back as a single
    # object rather than a list -- treat it as a one-entry directory
    # rather than raising, since "iac_path=main.tf" is a reasonable thing
    # to type.
    if isinstance(body, dict):
        return [_Entry(path=body["path"], kind="file")]
    return [_Entry(path=e["path"], kind=e["type"]) for e in body]


def _fetch_file(client: httpx.Client, owner: str, repo: str, branch: str, path: str) -> str:
    url = f"{_API}/repos/{owner}/{repo}/contents/{path}"
    response = client.get(
        url,
        params={"ref": branch},
        headers={"Accept": "application/vnd.github.raw"},
    )
    if response.status_code >= 400:
        raise ValueError(_explain(response, owner, repo, branch, path))
    return response.text


def _fetch_terraform_files(
    repo_url: str, branch: str, token: str, iac_path: str
) -> dict[str, str]:
    """`{filepath: content}` for every `.tf` file under `iac_path`.

    Raises `ValueError` with a specific, human reason for anything this
    can explain (bad token, missing repo/branch/path, no .tf files
    found) -- caught by `verify()` and shown to the user as-is, the same
    split `connections/gcp.py` uses between an explainable `ValueError`
    and a generic "could not reach the provider" exception.
    """
    owner, repo = _owner_repo(repo_url)
    path = (iac_path or "").strip("/")
    if not token.strip():
        raise ValueError("A GitHub token that can read this repository is required.")

    files: dict[str, str] = {}
    # A running counter checked from INSIDE walk(), not measured after the
    # fact -- a plain local re-assigned in the closure would need
    # `nonlocal`, so a one-element list is the simplest mutable cell that
    # both walk() and this function can see the current value of.
    bytes_so_far = [0]

    with httpx.Client(
        timeout=_TIMEOUT,
        headers={
            "Authorization": f"Bearer {token}",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
        },
    ) as client:

        def walk(dir_path: str, depth: int) -> None:
            if len(files) >= _MAX_FILES or bytes_so_far[0] >= _MAX_BYTES:
                return
            for entry in _list_dir(client, owner, repo, branch, dir_path):
                if len(files) >= _MAX_FILES or bytes_so_far[0] >= _MAX_BYTES:
                    return
                if entry.kind == "dir":
                    if depth < _MAX_DEPTH:
                        walk(entry.path, depth + 1)
                    continue
                if not entry.path.endswith(".tf"):
                    continue
                content = _fetch_file(client, owner, repo, branch, entry.path)
                files[entry.path] = content
                bytes_so_far[0] += len(content.encode("utf-8", errors="ignore"))

        walk(path, 0)

    if not files:
        raise ValueError(
            f"No .tf files found under {iac_path or '/'!r} on branch "
            f"{branch!r} of {owner}/{repo}."
        )
    return files


def _unquote(value):
    """hcl2 leaves a quoted string's literal quote characters IN the
    Python string (`'"t3.medium"'`, not `'t3.medium'`) -- confirmed
    directly against this library's actual output, not assumed. Applies
    to block labels too, since those come back the same way."""
    if isinstance(value, str) and len(value) >= 2 and value[0] == '"' and value[-1] == '"':
        return value[1:-1]
    return value


def _is_variable_ref(value) -> bool:
    """A bare `var.x` reference round-trips through hcl2 as the string
    `"${var.x}"` -- this is a reference this module does not resolve,
    not a literal size, and must be reported as unpriced rather than
    priced as the literal text `${var.x}`."""
    return isinstance(value, str) and value.strip().startswith("${")


def _find_region(files: dict[str, str], hcl2_module) -> str:
    for content in files.values():
        try:
            parsed = hcl2_module.load(io.StringIO(content))
        except Exception:
            continue
        for block in parsed.get("variable", []):
            for raw_label, attrs in block.items():
                label = _unquote(raw_label)
                if label not in ("aws_region", "region"):
                    continue
                default = _unquote(attrs.get("default"))
                if isinstance(default, str) and default and not _is_variable_ref(default):
                    return default
    return _DEFAULT_REGION


def _parse_and_price(
    files: dict[str, str], region: str, dsn: str | None = None
) -> tuple[list[dict], list[str], Decimal]:
    """`(items, missing, total)` -- the same shape
    `/describe/terraform/inspect` already returns `items` in, so the
    frontend has prior art to render against."""
    import hcl2

    provider = "aws"
    items: list[dict] = []
    missing: list[str] = []
    total = Decimal(0)

    def price_flat(label: str, category: str, sku: str) -> None:
        nonlocal total
        point = store.get_price(provider, region, category, sku, dsn=dsn)
        if point is None:
            missing.append(f"{label}: no catalog price for {sku!r} in {region}")
            return
        monthly = point.price_usd * HOURS_PER_MONTH
        items.append({"label": label, "sku": sku, "monthly": float(monthly)})
        total += monthly

    for filename, content in files.items():
        try:
            parsed = hcl2.load(io.StringIO(content))
        except Exception as exc:
            missing.append(f"{filename}: could not parse as HCL ({exc})")
            continue

        for module_block in parsed.get("module", []):
            for raw_label, attrs in module_block.items():
                label = _unquote(raw_label)
                source = _unquote(attrs.get("source", ""))

                if "terraform-aws-modules/autoscaling/aws" in source:
                    instance_type = attrs.get("instance_type")
                    if _is_variable_ref(instance_type):
                        missing.append(
                            f'module "{label}" (compute): instance_type comes '
                            "from a Terraform variable this scan did not "
                            "resolve, not a literal value"
                        )
                        continue
                    instance_type = _unquote(instance_type)
                    if not instance_type:
                        missing.append(f'module "{label}" (compute): no instance_type found')
                        continue
                    price_flat(f"Compute ({label})", "compute", instance_type)

                elif "terraform-aws-modules/rds/aws" in source:
                    instance_class = attrs.get("instance_class")
                    if _is_variable_ref(instance_class):
                        missing.append(
                            f'module "{label}" (database): instance_class '
                            "comes from a Terraform variable this scan did "
                            "not resolve, not a literal value"
                        )
                        continue
                    instance_class = _unquote(instance_class)
                    if not instance_class:
                        missing.append(f'module "{label}" (database): no instance_class found')
                        continue
                    # terraform-aws-modules/rds defaults multi_az to false
                    # when unset, so treating "not present" as False is
                    # matching Terraform's own default, not guessing.
                    multi_az = attrs.get("multi_az") is True
                    sku = f"{instance_class}:multi-az" if multi_az else instance_class
                    price_flat(f"Database ({label})", "database", sku)

                elif "terraform-aws-modules/alb/aws" in source:
                    price_flat(f"Load balancer ({label})", "loadbalancer", "alb")

                elif "terraform-aws-modules/s3-bucket/aws" in source:
                    # This module's own arguments never carry a bucket
                    # size -- there is no literal in the .tf that would
                    # let this price it without inventing a GB figure.
                    missing.append(
                        f'module "{label}" (object storage): bucket size is '
                        "not declared in Terraform, so it cannot be priced "
                        "from code alone"
                    )

        for resource_block in parsed.get("resource", []):
            for raw_type, labeled in resource_block.items():
                if _unquote(raw_type) != "aws_ecs_task_definition":
                    continue
                for raw_label, attrs in labeled.items():
                    label = _unquote(raw_label)
                    cpu, memory = attrs.get("cpu"), attrs.get("memory")
                    if _is_variable_ref(cpu) or _is_variable_ref(memory) or cpu is None or memory is None:
                        missing.append(
                            f'resource "aws_ecs_task_definition" "{label}": '
                            "cpu/memory is not a literal value this scan "
                            "can price"
                        )
                        continue
                    try:
                        vcpu = Decimal(str(cpu)) / Decimal(1024)
                        memory_gb = Decimal(str(memory)) / Decimal(1024)
                    except Exception:
                        missing.append(
                            f'resource "aws_ecs_task_definition" "{label}": '
                            "cpu/memory could not be read as numbers"
                        )
                        continue
                    arch = "x86_64"
                    for platform in attrs.get("runtime_platform", []):
                        if _unquote(platform.get("cpu_architecture")) == "ARM64":
                            arch = "arm64"
                    prefix = "fargate:arm-" if arch == "arm64" else "fargate:"
                    vcpu_point = store.get_price(provider, region, "fargate", f"{prefix}vcpu-hour", dsn=dsn)
                    gb_point = store.get_price(provider, region, "fargate", f"{prefix}gb-hour", dsn=dsn)
                    if vcpu_point is None or gb_point is None:
                        missing.append(
                            f'resource "aws_ecs_task_definition" "{label}": '
                            f"no Fargate catalog price in {region}"
                        )
                        continue
                    monthly = (vcpu_point.price_usd * vcpu + gb_point.price_usd * memory_gb) * HOURS_PER_MONTH
                    items.append({
                        "label": f"Fargate task ({label})",
                        "sku": f"{vcpu}vCPU/{memory_gb}GB",
                        "monthly": float(monthly),
                    })
                    total += monthly

    return items, missing, total


def setup(config: dict) -> Setup:
    return Setup(
        grants=(
            "Read-only access to one repository's Terraform files. "
            "WhichCloud reads .tf files under the path you name, parses "
            "the resources they declare, and prices them against its own "
            "catalog -- it never reads application code, issues or pull "
            "requests, and the token is never stored: it is used once, "
            "for this scan, and discarded."
        ),
        stores_secret=False,
        steps=[
            SetupStep(
                title="Create a fine-grained personal access token",
                body=(
                    "GitHub → Settings → Developer settings → Fine-grained "
                    "tokens. Grant it Contents: Read-only on the one "
                    "repository you want scanned -- nothing else."
                ),
                snippet="https://github.com/settings/personal-access-tokens/new",
                language="url",
            ),
            SetupStep(
                title="Tell us the repository and the Terraform path",
                body=(
                    "The repo (owner/repo or its URL), the branch, and the "
                    "directory your .tf files live in (e.g. terraform/)."
                ),
            ),
        ],
    )


def verify(config: dict, secret: str = "") -> VerifyResult:
    repo_url = str(config.get("repo_url") or "")
    branch = str(config.get("branch") or "main")
    token = str(config.get("github_token") or secret or "")
    iac_path = str(config.get("iac_path") or "")

    try:
        owner, repo = _owner_repo(repo_url)
    except ValueError as exc:
        return VerifyResult(ok=False, message=str(exc))

    try:
        files = _fetch_terraform_files(repo_url, branch, token, iac_path)
    except ValueError as exc:
        return VerifyResult(ok=False, message=str(exc))
    except Exception as exc:
        return VerifyResult(ok=False, message=f"Could not reach GitHub: {exc}")

    import hcl2 as hcl2_module
    region = _find_region(files, hcl2_module)

    try:
        items, missing, total = _parse_and_price(files, region)
    except Exception as exc:
        return VerifyResult(ok=False, message=f"Could not price this repository's Terraform: {exc}")

    if not items and not missing:
        return VerifyResult(
            ok=False,
            message=(
                f"Found {len(files)} .tf file(s) under {iac_path or '/'!r} "
                "but no recognised AWS resources (compute, database, load "
                "balancer, Fargate task, or S3 bucket module)."
            ),
        )

    summary = f"Found {len(items)} priced resource(s) across {len(files)} file(s), ~${total:.2f}/mo."
    if missing:
        summary += f" {len(missing)} resource(s) could not be priced from code alone."

    return VerifyResult(
        ok=True,
        account_id=f"{owner}/{repo}",
        message=summary,
        data={"items": items, "missing": missing, "monthly_cost": float(total), "region": region},
    )
