import type { ShowcaseData } from "@/components/landing/HeroShowcase";
import type { Scenario } from "@/components/landing/AskDemo";
import type { CatalogRow, Option } from "@/lib/api";
import defaultShopData from "./defaultShopArchitecture.json";

export const DEFAULT_SHOWCASE_DATA: ShowcaseData = {
  chart: {
    categories: [
      "Audit logging",
      "Authentication (MAU)",
      "Backup storage",
      "CDN data transfer",
      "Cache",
      "Compute",
      "DNS hosted zone",
      "DNS queries",
      "Database read replica",
      "Database storage",
      "Load balancer",
      "Monitoring",
      "NAT data processing",
      "NAT gateway",
      "Object storage (infrequent access)",
      "Object storage (standard)",
      "TLS certificate",
      "VPC flow logs",
    ],
    clouds: [
      {
        id: "gcp",
        label: "Google Cloud",
        total: 2668.73,
        segments: [
          { label: "Audit logging", value: 0.5 },
          { label: "Authentication (MAU)", value: 965 },
          { label: "Backup storage", value: 40 },
          { label: "CDN data transfer", value: 450 },
          { label: "Cache", value: 24.82 },
          { label: "Compute", value: 205.18 },
          { label: "DNS hosted zone", value: 0.2 },
          { label: "DNS queries", value: 40 },
          { label: "Database read replica", value: 485.89 },
          { label: "Database storage", value: 40.8 },
          { label: "Load balancer", value: 21.9 },
          { label: "Monitoring", value: 2.55 },
          { label: "NAT data processing", value: 225 },
          { label: "NAT gateway", value: 4.09 },
          { label: "Object storage (infrequent access)", value: 19.2 },
          { label: "Object storage (standard)", value: 18.4 },
          { label: "TLS certificate", value: 0.2 },
          { label: "VPC flow logs", value: 125 },
        ],
      },
      {
        id: "azure",
        label: "Microsoft Azure",
        total: 2702.41,
        segments: [
          { label: "Audit logging", value: 0 },
          { label: "Authentication (MAU)", value: 965 },
          { label: "Backup storage", value: 49.2 },
          { label: "CDN data transfer", value: 545 },
          { label: "Cache", value: 49.64 },
          { label: "Compute", value: 154.33 },
          { label: "DNS hosted zone", value: 0.5 },
          { label: "DNS queries", value: 40 },
          { label: "Database read replica", value: 572.32 },
          { label: "Database storage", value: 13.1 },
          { label: "Load balancer", value: 18.25 },
          { label: "Monitoring", value: 0.02 },
          { label: "NAT data processing", value: 225 },
          { label: "NAT gateway", value: 32.85 },
          { label: "Object storage (infrequent access)", value: 13.2 },
          { label: "Object storage (standard)", value: 24 },
          { label: "TLS certificate", value: 0 },
          { label: "VPC flow logs", value: 0 },
        ],
      },
      {
        id: "aws",
        label: "AWS",
        total: 3016.57,
        segments: [
          { label: "Audit logging", value: 0 },
          { label: "Authentication (MAU)", value: 920 },
          { label: "Backup storage", value: 110 },
          { label: "CDN data transfer", value: 545 },
          { label: "Cache", value: 40.15 },
          { label: "Compute", value: 189.22 },
          { label: "DNS hosted zone", value: 0.5 },
          { label: "DNS queries", value: 40 },
          { label: "Database read replica", value: 385.73 },
          { label: "Database storage", value: 26.2 },
          { label: "Load balancer", value: 17.45 },
          { label: "Monitoring", value: 9 },
          { label: "NAT data processing", value: 280 },
          { label: "NAT gateway", value: 81.76 },
          { label: "Object storage (infrequent access)", value: 16.56 },
          { label: "Object storage (standard)", value: 20 },
          { label: "TLS certificate", value: 0 },
          { label: "VPC flow logs", value: 335 },
        ],
      },
    ],
  },
  quote: "a video streaming API for India, busy all day",
  breakdown: [
    { label: "Authentication (MAU)", sku: "identityplatform:mau", monthly: 965 },
    { label: "Database (Multi-AZ)", sku: "db-custom-4-16384:multi-az", monthly: 485.89 },
    { label: "Database read replica", sku: "db-custom-4-16384", monthly: 485.89 },
    { label: "CDN data transfer", sku: "cloudcdn:cache-egress", monthly: 450 },
    { label: "NAT data processing", sku: "cloudnat:gb-processed", monthly: 225 },
  ],
  total: 3224.81,
  saved: 624.6,
  techniquesTested: 25,
  catalogSize: 37878,
  applied: [
    {
      name: "Commit to a year of usage (Savings Plan / Reserved / CUD)",
      saved: 295.94,
      versus: "t4g.xlarge",
      category: "compute",
    },
    {
      name: "ARM instances for the managed database",
      saved: 262.07,
      versus: "db.t2.xlarge:multi-az",
      category: "database",
    },
    {
      name: "Burstable instances for workloads that idle",
      saved: 33.87,
      versus: "m6g.xlarge",
      category: "compute",
    },
    {
      name: "ARM-based compute (AWS Graviton / Azure Ampere / GCP Axion)",
      saved: 19.27,
      versus: "t3a.xlarge:commit1yr",
      category: "compute",
    },
  ],
  advisory: [
    "Serve static assets from egress-free storage",
    "Cut egress before cutting compute",
    "ARM-based managed cache nodes",
  ],
};

export const DEFAULT_DEMO_SCENARIOS: Scenario[] = [
  {
    question: "An online shop for India, traffic comes in spikes",
    chips: ["web", "spiky", "medium", "india"],
    rows: [
      { provider: "gcp", label: "Google Cloud", monthly: "$250/mo", cheapest: true },
      { provider: "azure", label: "Microsoft Azure", monthly: "$262/mo", cheapest: false },
      { provider: "aws", label: "AWS", monthly: "$347/mo", cheapest: false },
    ],
  },
  {
    question: "A read-heavy API, steady traffic all day",
    chips: ["api", "steady", "medium", "india"],
    rows: [
      { provider: "gcp", label: "Google Cloud", monthly: "$190/mo", cheapest: true },
      { provider: "azure", label: "Microsoft Azure", monthly: "$199/mo", cheapest: false },
      { provider: "aws", label: "AWS", monthly: "$272/mo", cheapest: false },
    ],
  },
  {
    question: "Overnight batch jobs, interruptions are fine",
    chips: ["batch", "steady", "low", "india"],
    rows: [
      { provider: "azure", label: "Microsoft Azure", monthly: "$19/mo", cheapest: true },
      { provider: "gcp", label: "Google Cloud", monthly: "$21/mo", cheapest: false },
      { provider: "aws", label: "AWS", monthly: "$24/mo", cheapest: false },
    ],
  },
];

export const DEFAULT_BY_PROVIDER: Record<string, Option> =
  defaultShopData as unknown as Record<string, Option>;

export const DEFAULT_REGIONS = ["india", "us-east", "eu-west", "singapore"];

export const DEFAULT_PRICE_TICKER_ROWS: CatalogRow[] = [
  {
    provider: "azure",
    region: "centralindia",
    sku: "Standard_B2pls_v2",
    name: "B2pls v2",
    vcpu: 2,
    memory_gb: 4,
    arch: "arm64",
    unit: "hour",
    hourly_usd: 0.0224,
    monthly_usd: 16.35,
    fetched_at: "2026-09-09T05:19:32.602378+00:00",
  },
  {
    provider: "aws",
    region: "ap-south-1",
    sku: "t4g.medium",
    name: "t4g.medium",
    vcpu: 2,
    memory_gb: 4,
    arch: "arm64",
    unit: "hour",
    hourly_usd: 0.0224,
    monthly_usd: 16.35,
    fetched_at: "2026-09-09T05:18:54.350335+00:00",
  },
  {
    provider: "aws",
    region: "ap-south-1",
    sku: "t3a.medium",
    name: "t3a.medium",
    vcpu: 2,
    memory_gb: 4,
    arch: "x86_64",
    unit: "hour",
    hourly_usd: 0.0246,
    monthly_usd: 17.96,
    fetched_at: "2026-09-09T05:18:54.350335+00:00",
  },
  {
    provider: "azure",
    region: "centralindia",
    sku: "Standard_B2als_v2",
    name: "B2als v2",
    vcpu: 2,
    memory_gb: 4,
    arch: "x86_64",
    unit: "hour",
    hourly_usd: 0.0246,
    monthly_usd: 17.96,
    fetched_at: "2026-09-09T05:19:32.602378+00:00",
  },
  {
    provider: "azure",
    region: "centralindia",
    sku: "Standard_D2pls_v6",
    name: "D2pls v6",
    vcpu: 2,
    memory_gb: 4,
    arch: "arm64",
    unit: "hour",
    hourly_usd: 0.0408,
    monthly_usd: 29.78,
    fetched_at: "2026-09-09T05:19:32.602378+00:00",
  },
  {
    provider: "aws",
    region: "ap-south-1",
    sku: "c6g.large",
    name: "c6g.large",
    vcpu: 2,
    memory_gb: 4,
    arch: "arm64",
    unit: "hour",
    hourly_usd: 0.0426,
    monthly_usd: 31.1,
    fetched_at: "2026-09-09T05:18:54.350335+00:00",
  },
  {
    provider: "azure",
    region: "centralindia",
    sku: "Standard_D2pls_v5",
    name: "Standard_D2pls_v5",
    vcpu: 2,
    memory_gb: 4,
    arch: "arm64",
    unit: "hour",
    hourly_usd: 0.0426,
    monthly_usd: 31.1,
    fetched_at: "2026-09-09T05:19:32.602378+00:00",
  },
  {
    provider: "aws",
    region: "ap-south-1",
    sku: "t4g.large",
    name: "t4g.large",
    vcpu: 2,
    memory_gb: 8,
    arch: "arm64",
    unit: "hour",
    hourly_usd: 0.0448,
    monthly_usd: 32.7,
    fetched_at: "2026-09-09T05:18:54.350335+00:00",
  },
  {
    provider: "azure",
    region: "centralindia",
    sku: "Standard_B2ps_v2",
    name: "B2ps v2",
    vcpu: 2,
    memory_gb: 8,
    arch: "arm64",
    unit: "hour",
    hourly_usd: 0.0448,
    monthly_usd: 32.7,
    fetched_at: "2026-09-09T05:19:32.602378+00:00",
  },
  {
    provider: "aws",
    region: "ap-south-1",
    sku: "t3.medium",
    name: "t3.medium",
    vcpu: 2,
    memory_gb: 4,
    arch: "x86_64",
    unit: "hour",
    hourly_usd: 0.0448,
    monthly_usd: 32.7,
    fetched_at: "2026-09-09T05:18:54.350335+00:00",
  },
  {
    provider: "azure",
    region: "centralindia",
    sku: "Standard_D2ps_v6",
    name: "D2ps v6",
    vcpu: 2,
    memory_gb: 8,
    arch: "arm64",
    unit: "hour",
    hourly_usd: 0.0462,
    monthly_usd: 33.73,
    fetched_at: "2026-09-09T05:19:32.602378+00:00",
  },
  {
    provider: "aws",
    region: "ap-south-1",
    sku: "c7g.large",
    name: "c7g.large",
    vcpu: 2,
    memory_gb: 4,
    arch: "arm64",
    unit: "hour",
    hourly_usd: 0.0491,
    monthly_usd: 35.84,
    fetched_at: "2026-09-09T05:18:54.350335+00:00",
  },
];
