/* GENERATED by scripts/build-icon-catalog.mjs -- do not edit by hand.
 *
 * Every vendored mark, so the palette can offer all of them. Regenerate after
 * adding icons:  node scripts/build-icon-catalog.mjs
 */

export type IconEntry = {
  id: string;
  provider: "aws" | "gcp" | "azure" | "group";
  name: string;
  icon: string;
};

export const ICON_CATALOG: IconEntry[] = [
  {
    "id": "aws:amplify",
    "provider": "aws",
    "name": "Amplify",
    "icon": "/icons/aws/amplify.png"
  },
  {
    "id": "aws:apigateway",
    "provider": "aws",
    "name": "API Gateway",
    "icon": "/icons/aws/apigateway.png"
  },
  {
    "id": "aws:appconfig",
    "provider": "aws",
    "name": "Appconfig",
    "icon": "/icons/aws/appconfig.png"
  },
  {
    "id": "aws:apprunner",
    "provider": "aws",
    "name": "Apprunner",
    "icon": "/icons/aws/apprunner.png"
  },
  {
    "id": "aws:appsync",
    "provider": "aws",
    "name": "Appsync",
    "icon": "/icons/aws/appsync.png"
  },
  {
    "id": "aws:athena",
    "provider": "aws",
    "name": "Athena",
    "icon": "/icons/aws/athena.png"
  },
  {
    "id": "aws:aurora",
    "provider": "aws",
    "name": "Aurora",
    "icon": "/icons/aws/aurora.png"
  },
  {
    "id": "aws:autoscaling",
    "provider": "aws",
    "name": "Autoscaling",
    "icon": "/icons/aws/autoscaling.png"
  },
  {
    "id": "aws:backup",
    "provider": "aws",
    "name": "Backup",
    "icon": "/icons/aws/backup.png"
  },
  {
    "id": "aws:batch",
    "provider": "aws",
    "name": "Batch",
    "icon": "/icons/aws/batch.png"
  },
  {
    "id": "aws:bedrock",
    "provider": "aws",
    "name": "Bedrock",
    "icon": "/icons/aws/bedrock.png"
  },
  {
    "id": "aws:certificatemanager",
    "provider": "aws",
    "name": "Certificatemanager",
    "icon": "/icons/aws/certificatemanager.png"
  },
  {
    "id": "aws:cloud9",
    "provider": "aws",
    "name": "Cloud9",
    "icon": "/icons/aws/cloud9.png"
  },
  {
    "id": "aws:cloudformation",
    "provider": "aws",
    "name": "CloudFormation",
    "icon": "/icons/aws/cloudformation.png"
  },
  {
    "id": "aws:cloudfront",
    "provider": "aws",
    "name": "CloudFront",
    "icon": "/icons/aws/cloudfront.png"
  },
  {
    "id": "aws:cloudhsm",
    "provider": "aws",
    "name": "Cloudhsm",
    "icon": "/icons/aws/cloudhsm.png"
  },
  {
    "id": "aws:cloudtrail",
    "provider": "aws",
    "name": "CloudTrail",
    "icon": "/icons/aws/cloudtrail.png"
  },
  {
    "id": "aws:cloudwatch",
    "provider": "aws",
    "name": "CloudWatch",
    "icon": "/icons/aws/cloudwatch.png"
  },
  {
    "id": "aws:codeartifact",
    "provider": "aws",
    "name": "Codeartifact",
    "icon": "/icons/aws/codeartifact.png"
  },
  {
    "id": "aws:codebuild",
    "provider": "aws",
    "name": "Codebuild",
    "icon": "/icons/aws/codebuild.png"
  },
  {
    "id": "aws:codecommit",
    "provider": "aws",
    "name": "Codecommit",
    "icon": "/icons/aws/codecommit.png"
  },
  {
    "id": "aws:codedeploy",
    "provider": "aws",
    "name": "Codedeploy",
    "icon": "/icons/aws/codedeploy.png"
  },
  {
    "id": "aws:codepipeline",
    "provider": "aws",
    "name": "Codepipeline",
    "icon": "/icons/aws/codepipeline.png"
  },
  {
    "id": "aws:cognito",
    "provider": "aws",
    "name": "Cognito",
    "icon": "/icons/aws/cognito.png"
  },
  {
    "id": "aws:comprehend",
    "provider": "aws",
    "name": "Comprehend",
    "icon": "/icons/aws/comprehend.png"
  },
  {
    "id": "aws:config",
    "provider": "aws",
    "name": "Config",
    "icon": "/icons/aws/config.png"
  },
  {
    "id": "aws:controltower",
    "provider": "aws",
    "name": "Controltower",
    "icon": "/icons/aws/controltower.png"
  },
  {
    "id": "aws:datafirehose",
    "provider": "aws",
    "name": "Datafirehose",
    "icon": "/icons/aws/datafirehose.png"
  },
  {
    "id": "aws:directconnect",
    "provider": "aws",
    "name": "Directconnect",
    "icon": "/icons/aws/directconnect.png"
  },
  {
    "id": "aws:documentdb",
    "provider": "aws",
    "name": "DocumentDB",
    "icon": "/icons/aws/documentdb.png"
  },
  {
    "id": "aws:dynamodb",
    "provider": "aws",
    "name": "DynamoDB",
    "icon": "/icons/aws/dynamodb.png"
  },
  {
    "id": "aws:ec2",
    "provider": "aws",
    "name": "EC2",
    "icon": "/icons/aws/ec2.png"
  },
  {
    "id": "aws:efs",
    "provider": "aws",
    "name": "EFS",
    "icon": "/icons/aws/efs.png"
  },
  {
    "id": "aws:elasticache",
    "provider": "aws",
    "name": "ElastiCache",
    "icon": "/icons/aws/elasticache.png"
  },
  {
    "id": "aws:elasticbeanstalk",
    "provider": "aws",
    "name": "Elasticbeanstalk",
    "icon": "/icons/aws/elasticbeanstalk.png"
  },
  {
    "id": "aws:elasticcontainerregistry",
    "provider": "aws",
    "name": "Elastic Container Registry",
    "icon": "/icons/aws/elasticcontainerregistry.png"
  },
  {
    "id": "aws:elasticcontainerservice",
    "provider": "aws",
    "name": "Elastic Container Service",
    "icon": "/icons/aws/elasticcontainerservice.png"
  },
  {
    "id": "aws:elastickubernetesservice",
    "provider": "aws",
    "name": "Elastic Kubernetes Service",
    "icon": "/icons/aws/elastickubernetesservice.png"
  },
  {
    "id": "aws:elasticloadbalancing",
    "provider": "aws",
    "name": "Elastic Load Balancing",
    "icon": "/icons/aws/elasticloadbalancing.png"
  },
  {
    "id": "aws:emr",
    "provider": "aws",
    "name": "EMR",
    "icon": "/icons/aws/emr.png"
  },
  {
    "id": "aws:eventbridge",
    "provider": "aws",
    "name": "Eventbridge",
    "icon": "/icons/aws/eventbridge.png"
  },
  {
    "id": "aws:fargate",
    "provider": "aws",
    "name": "Fargate",
    "icon": "/icons/aws/fargate.png"
  },
  {
    "id": "aws:fsx",
    "provider": "aws",
    "name": "Fsx",
    "icon": "/icons/aws/fsx.png"
  },
  {
    "id": "aws:globalaccelerator",
    "provider": "aws",
    "name": "Globalaccelerator",
    "icon": "/icons/aws/globalaccelerator.png"
  },
  {
    "id": "aws:glue",
    "provider": "aws",
    "name": "Glue",
    "icon": "/icons/aws/glue.png"
  },
  {
    "id": "aws:guardduty",
    "provider": "aws",
    "name": "GuardDuty",
    "icon": "/icons/aws/guardduty.png"
  },
  {
    "id": "aws:identityandaccessmanagement",
    "provider": "aws",
    "name": "Identity and Access Management",
    "icon": "/icons/aws/identityandaccessmanagement.png"
  },
  {
    "id": "aws:inspector",
    "provider": "aws",
    "name": "Inspector",
    "icon": "/icons/aws/inspector.png"
  },
  {
    "id": "aws:iotcore",
    "provider": "aws",
    "name": "Iotcore",
    "icon": "/icons/aws/iotcore.png"
  },
  {
    "id": "aws:keymanagementservice",
    "provider": "aws",
    "name": "Key Management Service",
    "icon": "/icons/aws/keymanagementservice.png"
  },
  {
    "id": "aws:keyspaces",
    "provider": "aws",
    "name": "Keyspaces",
    "icon": "/icons/aws/keyspaces.png"
  },
  {
    "id": "aws:kinesis",
    "provider": "aws",
    "name": "Kinesis",
    "icon": "/icons/aws/kinesis.png"
  },
  {
    "id": "aws:lakeformation",
    "provider": "aws",
    "name": "Lakeformation",
    "icon": "/icons/aws/lakeformation.png"
  },
  {
    "id": "aws:lambda",
    "provider": "aws",
    "name": "Lambda",
    "icon": "/icons/aws/lambda.png"
  },
  {
    "id": "aws:lightsail",
    "provider": "aws",
    "name": "Lightsail",
    "icon": "/icons/aws/lightsail.png"
  },
  {
    "id": "aws:macie",
    "provider": "aws",
    "name": "Macie",
    "icon": "/icons/aws/macie.png"
  },
  {
    "id": "aws:managedstreamingforapachekafka",
    "provider": "aws",
    "name": "Managedstreamingforapachekafka",
    "icon": "/icons/aws/managedstreamingforapachekafka.png"
  },
  {
    "id": "aws:memorydb",
    "provider": "aws",
    "name": "Memorydb",
    "icon": "/icons/aws/memorydb.png"
  },
  {
    "id": "aws:mq",
    "provider": "aws",
    "name": "Mq",
    "icon": "/icons/aws/mq.png"
  },
  {
    "id": "aws:neptune",
    "provider": "aws",
    "name": "Neptune",
    "icon": "/icons/aws/neptune.png"
  },
  {
    "id": "aws:networkfirewall",
    "provider": "aws",
    "name": "Networkfirewall",
    "icon": "/icons/aws/networkfirewall.png"
  },
  {
    "id": "aws:opensearchservice",
    "provider": "aws",
    "name": "Opensearchservice",
    "icon": "/icons/aws/opensearchservice.png"
  },
  {
    "id": "aws:organizations",
    "provider": "aws",
    "name": "Organizations",
    "icon": "/icons/aws/organizations.png"
  },
  {
    "id": "aws:polly",
    "provider": "aws",
    "name": "Polly",
    "icon": "/icons/aws/polly.png"
  },
  {
    "id": "aws:rds",
    "provider": "aws",
    "name": "RDS",
    "icon": "/icons/aws/rds.png"
  },
  {
    "id": "aws:redshift",
    "provider": "aws",
    "name": "Redshift",
    "icon": "/icons/aws/redshift.png"
  },
  {
    "id": "aws:rekognition",
    "provider": "aws",
    "name": "Rekognition",
    "icon": "/icons/aws/rekognition.png"
  },
  {
    "id": "aws:route53",
    "provider": "aws",
    "name": "Route 53",
    "icon": "/icons/aws/route53.png"
  },
  {
    "id": "aws:sagemakerai",
    "provider": "aws",
    "name": "Sagemakerai",
    "icon": "/icons/aws/sagemakerai.png"
  },
  {
    "id": "aws:secretsmanager",
    "provider": "aws",
    "name": "Secrets Manager",
    "icon": "/icons/aws/secretsmanager.png"
  },
  {
    "id": "aws:securityhub",
    "provider": "aws",
    "name": "Securityhub",
    "icon": "/icons/aws/securityhub.png"
  },
  {
    "id": "aws:shield",
    "provider": "aws",
    "name": "Shield",
    "icon": "/icons/aws/shield.png"
  },
  {
    "id": "aws:simplenotificationservice",
    "provider": "aws",
    "name": "Simplenotificationservice",
    "icon": "/icons/aws/simplenotificationservice.png"
  },
  {
    "id": "aws:simplequeueservice",
    "provider": "aws",
    "name": "Simplequeueservice",
    "icon": "/icons/aws/simplequeueservice.png"
  },
  {
    "id": "aws:simplestorageservice",
    "provider": "aws",
    "name": "Simplestorageservice",
    "icon": "/icons/aws/simplestorageservice.png"
  },
  {
    "id": "aws:stepfunctions",
    "provider": "aws",
    "name": "Step Functions",
    "icon": "/icons/aws/stepfunctions.png"
  },
  {
    "id": "aws:storagegateway",
    "provider": "aws",
    "name": "Storagegateway",
    "icon": "/icons/aws/storagegateway.png"
  },
  {
    "id": "aws:systemsmanager",
    "provider": "aws",
    "name": "Systems Manager",
    "icon": "/icons/aws/systemsmanager.png"
  },
  {
    "id": "aws:textract",
    "provider": "aws",
    "name": "Textract",
    "icon": "/icons/aws/textract.png"
  },
  {
    "id": "aws:timestream",
    "provider": "aws",
    "name": "Timestream",
    "icon": "/icons/aws/timestream.png"
  },
  {
    "id": "aws:transitgateway",
    "provider": "aws",
    "name": "Transitgateway",
    "icon": "/icons/aws/transitgateway.png"
  },
  {
    "id": "aws:trustedadvisor",
    "provider": "aws",
    "name": "Trustedadvisor",
    "icon": "/icons/aws/trustedadvisor.png"
  },
  {
    "id": "aws:vpc",
    "provider": "aws",
    "name": "VPC",
    "icon": "/icons/aws/vpc.png"
  },
  {
    "id": "aws:vpcnatgateway",
    "provider": "aws",
    "name": "Vpcnatgateway",
    "icon": "/icons/aws/vpcnatgateway.png"
  },
  {
    "id": "aws:waf",
    "provider": "aws",
    "name": "WAF",
    "icon": "/icons/aws/waf.png"
  },
  {
    "id": "aws:xray",
    "provider": "aws",
    "name": "X-Ray",
    "icon": "/icons/aws/xray.png"
  },
  {
    "id": "gcp:bigquery",
    "provider": "gcp",
    "name": "BigQuery",
    "icon": "/icons/gcp/bigquery.png"
  },
  {
    "id": "gcp:certmanager",
    "provider": "gcp",
    "name": "Certmanager",
    "icon": "/icons/gcp/certmanager.png"
  },
  {
    "id": "gcp:cloud-cdn",
    "provider": "gcp",
    "name": "Cloud Cdn",
    "icon": "/icons/gcp/cloud-cdn.svg"
  },
  {
    "id": "gcp:cloud-load-balancing",
    "provider": "gcp",
    "name": "Cloud Load Balancing",
    "icon": "/icons/gcp/cloud-load-balancing.svg"
  },
  {
    "id": "gcp:cloud-monitoring",
    "provider": "gcp",
    "name": "Cloud Monitoring",
    "icon": "/icons/gcp/cloud-monitoring.svg"
  },
  {
    "id": "gcp:cloud-sql",
    "provider": "gcp",
    "name": "Cloud Sql",
    "icon": "/icons/gcp/cloud-sql.svg"
  },
  {
    "id": "gcp:cloud-storage",
    "provider": "gcp",
    "name": "Cloud Storage",
    "icon": "/icons/gcp/cloud-storage.svg"
  },
  {
    "id": "gcp:cloudarmor",
    "provider": "gcp",
    "name": "Cloudarmor",
    "icon": "/icons/gcp/cloudarmor.png"
  },
  {
    "id": "gcp:cloudcdn",
    "provider": "gcp",
    "name": "Cloudcdn",
    "icon": "/icons/gcp/cloudcdn.png"
  },
  {
    "id": "gcp:clouddns",
    "provider": "gcp",
    "name": "Cloud DNS",
    "icon": "/icons/gcp/clouddns.png"
  },
  {
    "id": "gcp:cloudfunctions",
    "provider": "gcp",
    "name": "Cloudfunctions",
    "icon": "/icons/gcp/cloudfunctions.png"
  },
  {
    "id": "gcp:cloudkms",
    "provider": "gcp",
    "name": "Cloudkms",
    "icon": "/icons/gcp/cloudkms.png"
  },
  {
    "id": "gcp:cloudlb",
    "provider": "gcp",
    "name": "Cloud Load Balancing",
    "icon": "/icons/gcp/cloudlb.png"
  },
  {
    "id": "gcp:cloudlogging",
    "provider": "gcp",
    "name": "Cloud Logging",
    "icon": "/icons/gcp/cloudlogging.png"
  },
  {
    "id": "gcp:cloudmonitoring",
    "provider": "gcp",
    "name": "Cloudmonitoring",
    "icon": "/icons/gcp/cloudmonitoring.png"
  },
  {
    "id": "gcp:cloudnat",
    "provider": "gcp",
    "name": "Cloudnat",
    "icon": "/icons/gcp/cloudnat.png"
  },
  {
    "id": "gcp:cloudrouter",
    "provider": "gcp",
    "name": "Cloudrouter",
    "icon": "/icons/gcp/cloudrouter.png"
  },
  {
    "id": "gcp:cloudrun",
    "provider": "gcp",
    "name": "Cloud Run",
    "icon": "/icons/gcp/cloudrun.png"
  },
  {
    "id": "gcp:cloudsql",
    "provider": "gcp",
    "name": "Cloud SQL",
    "icon": "/icons/gcp/cloudsql.png"
  },
  {
    "id": "gcp:cloudstorage",
    "provider": "gcp",
    "name": "Cloud Storage",
    "icon": "/icons/gcp/cloudstorage.png"
  },
  {
    "id": "gcp:compute-engine",
    "provider": "gcp",
    "name": "Compute Engine",
    "icon": "/icons/gcp/compute-engine.svg"
  },
  {
    "id": "gcp:computeengine",
    "provider": "gcp",
    "name": "Compute Engine",
    "icon": "/icons/gcp/computeengine.png"
  },
  {
    "id": "gcp:filestore",
    "provider": "gcp",
    "name": "Filestore",
    "icon": "/icons/gcp/filestore.png"
  },
  {
    "id": "gcp:firestore",
    "provider": "gcp",
    "name": "Firestore",
    "icon": "/icons/gcp/firestore.png"
  },
  {
    "id": "gcp:firewallrules",
    "provider": "gcp",
    "name": "Firewallrules",
    "icon": "/icons/gcp/firewallrules.png"
  },
  {
    "id": "gcp:gke",
    "provider": "gcp",
    "name": "Gke",
    "icon": "/icons/gcp/gke.png"
  },
  {
    "id": "gcp:iam",
    "provider": "gcp",
    "name": "IAM",
    "icon": "/icons/gcp/iam.png"
  },
  {
    "id": "gcp:memorystore",
    "provider": "gcp",
    "name": "Memorystore",
    "icon": "/icons/gcp/memorystore.png"
  },
  {
    "id": "gcp:memorystore",
    "provider": "gcp",
    "name": "Memorystore",
    "icon": "/icons/gcp/memorystore.svg"
  },
  {
    "id": "gcp:pubsub",
    "provider": "gcp",
    "name": "Pubsub",
    "icon": "/icons/gcp/pubsub.png"
  },
  {
    "id": "gcp:routes",
    "provider": "gcp",
    "name": "Routes",
    "icon": "/icons/gcp/routes.png"
  },
  {
    "id": "gcp:scc",
    "provider": "gcp",
    "name": "Scc",
    "icon": "/icons/gcp/scc.png"
  },
  {
    "id": "gcp:secretmanager",
    "provider": "gcp",
    "name": "Secretmanager",
    "icon": "/icons/gcp/secretmanager.png"
  },
  {
    "id": "gcp:vpcnetwork",
    "provider": "gcp",
    "name": "Vpcnetwork",
    "icon": "/icons/gcp/vpcnetwork.png"
  },
  {
    "id": "azure:aks",
    "provider": "azure",
    "name": "AKS",
    "icon": "/icons/azure/aks.png"
  },
  {
    "id": "azure:appgateway",
    "provider": "azure",
    "name": "Application Gateway",
    "icon": "/icons/azure/appgateway.png"
  },
  {
    "id": "azure:azuredns",
    "provider": "azure",
    "name": "Azure DNS",
    "icon": "/icons/azure/azuredns.png"
  },
  {
    "id": "azure:blob",
    "provider": "azure",
    "name": "Blob Storage",
    "icon": "/icons/azure/blob.png"
  },
  {
    "id": "azure:cache-redis",
    "provider": "azure",
    "name": "Cache Redis",
    "icon": "/icons/azure/cache-redis.svg"
  },
  {
    "id": "azure:cosmosdb",
    "provider": "azure",
    "name": "Cosmos DB",
    "icon": "/icons/azure/cosmosdb.png"
  },
  {
    "id": "azure:defender",
    "provider": "azure",
    "name": "Defender",
    "icon": "/icons/azure/defender.png"
  },
  {
    "id": "azure:front-door",
    "provider": "azure",
    "name": "Front Door",
    "icon": "/icons/azure/front-door.svg"
  },
  {
    "id": "azure:frontdoor",
    "provider": "azure",
    "name": "Frontdoor",
    "icon": "/icons/azure/frontdoor.png"
  },
  {
    "id": "azure:frontdoorwaf",
    "provider": "azure",
    "name": "Frontdoorwaf",
    "icon": "/icons/azure/frontdoorwaf.png"
  },
  {
    "id": "azure:functions",
    "provider": "azure",
    "name": "Functions",
    "icon": "/icons/azure/functions.png"
  },
  {
    "id": "azure:keyvault",
    "provider": "azure",
    "name": "Keyvault",
    "icon": "/icons/azure/keyvault.png"
  },
  {
    "id": "azure:keyvaultcert",
    "provider": "azure",
    "name": "Keyvaultcert",
    "icon": "/icons/azure/keyvaultcert.png"
  },
  {
    "id": "azure:load-balancer",
    "provider": "azure",
    "name": "Load Balancer",
    "icon": "/icons/azure/load-balancer.svg"
  },
  {
    "id": "azure:monitor",
    "provider": "azure",
    "name": "Monitor",
    "icon": "/icons/azure/monitor.svg"
  },
  {
    "id": "azure:natgateway",
    "provider": "azure",
    "name": "Natgateway",
    "icon": "/icons/azure/natgateway.png"
  },
  {
    "id": "azure:nsg",
    "provider": "azure",
    "name": "Nsg",
    "icon": "/icons/azure/nsg.png"
  },
  {
    "id": "azure:postgresql",
    "provider": "azure",
    "name": "Postgresql",
    "icon": "/icons/azure/postgresql.png"
  },
  {
    "id": "azure:postgresql",
    "provider": "azure",
    "name": "Postgresql",
    "icon": "/icons/azure/postgresql.svg"
  },
  {
    "id": "azure:redis",
    "provider": "azure",
    "name": "Redis",
    "icon": "/icons/azure/redis.png"
  },
  {
    "id": "azure:routetable",
    "provider": "azure",
    "name": "Routetable",
    "icon": "/icons/azure/routetable.png"
  },
  {
    "id": "azure:storage",
    "provider": "azure",
    "name": "Storage",
    "icon": "/icons/azure/storage.svg"
  },
  {
    "id": "azure:subnet",
    "provider": "azure",
    "name": "Subnet",
    "icon": "/icons/azure/subnet.png"
  },
  {
    "id": "azure:synapse",
    "provider": "azure",
    "name": "Synapse",
    "icon": "/icons/azure/synapse.png"
  },
  {
    "id": "azure:virtual-machines",
    "provider": "azure",
    "name": "Virtual Machines",
    "icon": "/icons/azure/virtual-machines.svg"
  },
  {
    "id": "azure:vm",
    "provider": "azure",
    "name": "Vm",
    "icon": "/icons/azure/vm.png"
  },
  {
    "id": "azure:vnet",
    "provider": "azure",
    "name": "Vnet",
    "icon": "/icons/azure/vnet.png"
  }
];

/** Boundary marks -- VPC, subnet, region. Kept apart because they frame
 *  other services rather than sitting beside them. */
export const GROUP_ICONS: IconEntry[] = [
  {
    "id": "group:account",
    "provider": "group",
    "name": "Account",
    "icon": "/icons/aws-groups/account.png"
  },
  {
    "id": "group:auto-scaling-group",
    "provider": "group",
    "name": "Auto Scaling Group",
    "icon": "/icons/aws-groups/auto-scaling-group.png"
  },
  {
    "id": "group:aws-cloud",
    "provider": "group",
    "name": "Aws Cloud",
    "icon": "/icons/aws-groups/aws-cloud.png"
  },
  {
    "id": "group:private-subnet",
    "provider": "group",
    "name": "Private Subnet",
    "icon": "/icons/aws-groups/private-subnet.png"
  },
  {
    "id": "group:public-subnet",
    "provider": "group",
    "name": "Public Subnet",
    "icon": "/icons/aws-groups/public-subnet.png"
  },
  {
    "id": "group:region",
    "provider": "group",
    "name": "Region",
    "icon": "/icons/aws-groups/region.png"
  },
  {
    "id": "group:vpc",
    "provider": "group",
    "name": "VPC",
    "icon": "/icons/aws-groups/vpc.png"
  }
];
